### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by tXambe** [noraj/haiti#122]
Hello,
when I execute the script I have this error:

```
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- haiti (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from ./haiti:7:in `<main>'
                                                                                        
```

My kernel version Debian 5.16.18-1  and my ruby version ruby 3.0.3p157

A greeting and thanks

**Comment by noraj** [comment]
Hi

1. how did you installed it?
2. what command do you use to run it?
3. Which version how haiti do you run?

**Comment by noraj** [comment]
I'll close for now as there is no information in the issue, feel free to post them and I'll re-open.
