### ISSUE TITLE
Add VeraCrypt / TrueCrypt

### ISSUE THREAD

**Issue by noraj** [noraj/haiti#154]
There are tons of variants listed at https://hashcat.net/wiki/doku.php?id=example_hashes

**Comment by Abhinandan-Khurana** [comment]
Hey! Can you please assign this issue to me.
I would love to contribute!

**Comment by noraj** [comment]
Thanks, You can work on it.

**Comment by Abhinandan-Khurana** [comment]
Do I need to add all the variants for VeraCrypt and TrueCrypt?
Also, I updated the prototypes.json but not getting the result when running the tool, even though while debugging I get the VeraCrypt varient  --> ```puts HashIdentifier::PROTOTYPES.inspect```
need a little help or direction..

**Comment by noraj** [comment]
You can see on the documentation page https://noraj.github.io/haiti/#/pages/install in the [Development](https://noraj.github.io/haiti/#/pages/install?id=development) section on the **No install** tab. How you can run the library or CLI app on the way while developing without installing it. You can also use `binding.irb` for debugging. You can also check your regexp are working online on https://regex101.com/ before coding.

**Comment by Abhinandan-Khurana** [comment]
Thank you for guiding me 
I'm still new to Ruby and might have missed a few things, but I wanted to contribute to the repo. I'll definitely use your tips as I continue to learn and contribute

**Comment by noraj** [comment]
@Abhinandan-Khurana Have you been able to work on this?

**Comment by noraj** [comment]
- [x] VC HC f70bdeafd9ba88b14523f31013a78e243f18b40f
- [x] TC HC 82bf5da2b78a5b82bcd9efaac72c887a2e8dc0d6
- [ ] TC JtR

**Comment by Abhinandan-Khurana** [comment]
Yes, I have done it, I'll do a pull request.
Sorry for the late reply.
