### ISSUE TITLE
Make Footer more attractive by adding Social Media Handles

### ISSUE THREAD

**Issue by parthksingh1** [noraj/haiti#158]
Please assign me this issue will implement and make footer more attractive

**Comment by noraj** [comment]
@parthksingh1 What footer are you talking about?

**Comment by parthksingh1** [comment]
![Screenshot_20231002_001640_Chrome.jpg](https://github.com/noraj/haiti/assets/128512586/9f807429-46c5-4e12-a045-4949b535ea43)

This one the Author one it is looking quite simple 
Adding social media handles will 
Engagement: Connect with users and foster community discussions around your project.
Visibility: Enhance project visibility as content gets shared or discussed on social platforms.
Feedback: Get direct user feedback and insights to iterate and improve the project.
Drive Traffic: Direct interested users from social platforms to your project page.
Trust: Show that the project is active and updated, building user trust.
Updates: Share project updates, milestones, and news effortlessly.
Networking: Connect with potential collaborators, contributors, or stakeholders.
Linking social media handles in your project helps in bridging the communication gap, expanding reach, and fostering an active community around your project.

**Comment by noraj** [comment]
This page is populated from the README.md, changing this would just be adding some badges.

https://hacktoberfest.com/participation/

> Avoid submitting low-quality pull/merge requests.
