### ISSUE TITLE
MD6

### ISSUE THREAD

**Issue by DJDarkCyber** [noraj/haiti#84]
haiti 3e4a89ab1672c40a68b6a65a703c3612a9ee3ad21b8c9b0146a5c8bfbef2d06a

SHA-256 [HC: 1400] [JtR: raw-sha256]
GOST R 34.11-94 [HC: 6900] [JtR: gost]
SHA3-256 [HC: 17400] [JtR: dynamic_380]
Keccak-256 [HC: 17800] [JtR: raw-keccak-256]
Snefru-256 [JtR: snefru-256]
RIPEMD-256 [JtR: dynamic_140]
Haval-256 (3 rounds) [JtR: haval-256-3]
Haval-256 (4 rounds) [JtR: dynamic_290]
Haval-256 (5 rounds) [JtR: dynamic_300]
GOST CryptoPro S-Box
Skein-256 [JtR: skein-256]
Skein-512(256)
PANAMA [JtR: dynamic_320]
BLAKE2-256
Umbraco HMAC-SHA1 [HC: 24800]

**Comment by noraj** [comment]
Oh! md6 is very rare, it's used nearly nowhere. It was submitted to the SHA3 competition but didn't win.

I'll add it if I find enough information about it.

- https://en.wikipedia.org/wiki/MD6
- [ ] http://people.csail.mit.edu/rivest/md6_report.pdf

- JtR support ❌ 
- HC support ❌
